apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: bulldok-deploy-pipeline
  namespace: nogada
spec:
  resources:
  - name: git-source
    type: git
  - name: docker-image
    type: image
  tasks:
  - name: build
    params:
    - name: TLSVERIFY
      value: "false"
    resources:
      inputs:
      - name: git-source
        resource: git-source
      outputs:
      - name: docker-image
        resource: docker-image
    taskRef:
      kind: Task
      name: s2i-java-8
  - name: deploy
    params:
    - name: ARGS
      value: rollout latest sam-bulldok
    runAfter:
    - build
    taskRef:
      kind: Task
      name: openshift-client
