apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: sam-bulldok
  name: sam-bulldok
  namespace: nogada
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: sam-bulldok
    deploymentconfig: sam-bulldok
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: sam-bulldok
        deploymentconfig: sam-bulldok
    spec:
      containers:
      - image: sam-bulldok:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: sam-bulldok
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - imageChangeParams:
      containerNames:
      - sam-bulldok
      from:
        kind: ImageStreamTag
        name: sam-bulldok:latest
        namespace: nogada
    type: ImageChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sam-bulldok
  name: sam-bulldok
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    app: sam-bulldok
    deploymentconfig: sam-bulldok
  sessionAffinity: None
  type: ClusterIP
---